language: go
go_import_path: github.com/matthewhartstonge/storage
go:
  - '1.8'
  - '1.9'
  - '1.10'

services:
  - mongodb

before_install:
  - mkdir -p $GOPATH/bin $GOPATH/pkg $GOPATH/src
  - go get github.com/mattn/goveralls
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure

script:
  - $GOPATH/bin/goveralls -service=travis-ci
