language: go
sudo: false
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

services:
  - mongodb

before_install:
  - mkdir -p $GOPATH/bin $GOPATH/pkg $GOPATH/src
  - go get github.com/mattn/goveralls

install:
  - go get

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

