language: go
go_import_path: github.com/matthewhartstonge/storage
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

services:
  - mongodb

before_install:
  - mkdir -p $GOPATH/bin $GOPATH/pkg $GOPATH/src
  - go get github.com/mattn/goveralls
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure -v

script:
  - $GOPATH/bin/goveralls -service=travis-ci
